> df<-read.csv("NewData.csv")
> plot(df$Global_active_power,type="l",axes=FALSE,ann=FALSE)
> box()
> axis(1,at=1,lab="Thu")
> axis(1,at=1440,lab="Fri")
> axis(1,at=2880,lab="Sat")
> axis(2,at=2)
> axis(2,at=0)
> axis(2,at=4)
> axis(2,at=6)
> title(ylab="Global Active Power (kilowatts)")
> dev.copy(png,"plot2.png")
> dev.off()
